// Mocks generated by Mockito 5.3.2 from annotations
// in pokedex/test/features/pokemon_list/domain/get_pokemon_list_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pokedex/src/features/pokemon_list/domain/entities/pokemon_entity.dart'
    as _i5;
import 'package:pokedex/src/features/pokemon_list/domain/repositories/pokemon_list_repository.dart'
    as _i2;

import 'get_pokemon_list_test.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePokemonListRepository_0 extends _i1.SmartFake
    implements _i2.PokemonListRepository {
  _FakePokemonListRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetPokemonListTest].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPokemonListTest extends _i1.Mock
    implements _i3.GetPokemonListTest {
  MockGetPokemonListTest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PokemonListRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakePokemonListRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.PokemonListRepository);
  @override
  _i4.Future<List<_i5.PokemonEntity>?> execute({required int? page}) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
          {#page: page},
        ),
        returnValue: _i4.Future<List<_i5.PokemonEntity>?>.value(),
      ) as _i4.Future<List<_i5.PokemonEntity>?>);
}
